<!--- PROOFED --->

# God's Testimony Concerning Man

<table>
<tr>
<td>Gen. 6:5–12</td>
<td>Eccl. 7:29</td>
<td>Rom. 3:9–19</td>
</tr>
<tr>
<td>Job 15:14–16</td>
<td>Isa. 53:6</td>
<td>Eph. 2:1–3</td>
</tr>
<tr>
<td>Psa. 14:1–3</td>
<td>John 15:18–24</td>
<td>Titus 3:3</td>
</tr>
<tr>
<td>Psa. 51:4–5</td>
<td>Rom. 1:21–32</td>
<td>1 John\ 5:19</td>
</tr>
</table>

[God knows us]{.smallcaps}. He knows what we are; he knows also what he meant us to be; and upon the difference between these two states he founds his testimony concerning us.

He is too loving to say anything needlessly severe; too true to say anything untrue; nor can he have any motive to misrepresent us; for he loves to tell of the good, not of the evil, that may be found in any of the works of his hands. He declared them “good,” “very good,” at first; and if he does not do so now, it is not because he would not, but because he cannot; for “all flesh has corrupted its way upon the earth,” (Gen. 6:12).

God’s testimony concerning man is, that he is a *sinner*. He bears witness *against* him, not *for* him, and testifies that “there is none righteous, no, not one;” that there is “none that doeth good;” none “that understandeth;” none that even *seeketh* after God, and still more none that *loveth* him. (Psa. 14:1–3; Rom 3:10–12.) God speaks of man kindly, but severely; as one yearning over a lost child, yet as one who will make no terms with sin, and will “by no means clear the guilty.” He declares man to be a *lost* one, a *stray* one, a *rebel*, nay a “[hater of God]{.smallcaps},” (Rom. 1:30); not a sinner occasionally, but a sinner always; not a sinner in part, with many good things about him; but wholly a sinner, with no compensating goodness; evil in heart as well as life, “dead in trespasses and sins,” (Eph. 2:1); an evil doer, and therefore under condemnation; an enemy of God, and therefore “under wrath;” a breaker of the righteous law, and therefore under “the curse of the law,” (Gal. 3:10).

Man has fallen! Not this man or that man, but the whole race. In Adam all have sinned; in Adam all have died. It is not that a few leaves have faded or been shaken down, but the tree has become corrupt, root and branch. The “flesh,” or “old man”—that is, each man as he is born into the world, a son of man, a fragment of humanity, a unit in Adam’s fallen body,—is “corrupt.” He not merely brings forth sin, but he carries it about with him, as his second self; nay, he is a “body” or mass of sin (Rom. 6:6), a “body of death” (Rom. 7:24), subject not to the law of God, but to “the law of sin,” (Rom 7:23). The Jew, educated under the most perfect of laws, and in the most favourable circumstances, was the best type of humanity,—of civilised, polished, educated humanity; the best specimen of the first Adam’s sons; yet God’s testimony concerning him is that he is “under sin,” that he has gone astray, and that he has “come short of the glory of God.”

The *outer* life of a man is not *the man*, just as the paint on a piece of timber is not the timber, and as the green moss upon the hard rock is not the rock itself. The picture of a man is not the man; it is but a skilful arrangement of colours which look like the man. So it is the bearing of the soul toward God that is the true state of the man. The man that loves God with all his heart is in a right state; the man that does not love him thus is in a wrong one. He is a sinner; because his heart is not right with God. He may think his life a good one, and others may think the same; but God counts him guilty, worthy of death and hell. The outward good cannot make up for the inward evil. The good deeds done to his fellow-men cannot be set off against his bad thoughts of God. And he must be full of these bad thoughts so long as he does not love this infinitely loveable and infinitely glorious Being with all his strength.

God’s testimony then concerning man is, that he does not love God with all his heart; nay, that he does not love him at all. Not to love our neighbour is sin; not to love a parent is greater sin; but not to love God, our divine parent, is greater sin still.

Man need not try to say a good word for himself, or to plead “not guilty,” unless he can shew that he loves, and has always loved God with his whole heart and soul. If he can truly say this, he is all right, he is not a sinner, and does not need pardon. He will find his way to the kingdom without the cross and without a Saviour. But, if he cannot say this, “his mouth is stopped,” and he is “guilty before God.” However favourably a good outward life may dispose himself and others to look upon his case just now, the verdict will go against him hereafter. This is *man’s day*, when man’s judgments prevail; but *God’s day* is coming, when the case shall be strictly tried upon its real merits. Then the Judge of all the earth shall do right, and the sinner be put to shame.

There is another and yet worse charge against him. He does not believe on the name of the Son of God, nor love the Christ of God. This is his sin of sins. That his heart is not right with God is the first charge against him. That his heart is not right with the Son of God is the second. And it is this second that is the crowning, crushing sin, carrying with it more terrible damnation than all other sins together. “He that believeth not is condemned already, *because he hath not believed* in the name of the only begotten Son of God,” (John 3:18). “He that believeth not God, hath made him a liar; *because he believeth not* the record which God gave of his Son,” (1 John 5:10). “He that *believeth not* shall be damned,” (Mark 16:16). Hence it was that the apostles preached “repentance toward God, and *faith* toward our Lord Jesus Christ,” (Acts 20:21). And hence it is that the first sin which the Holy Spirit brings home to a man is *unbelief*; “when he is come, he will reprove the world of sin, *because they believe not* on me,” (John 16:8–9).

Such is God’s condemnation of man. Of this the whole Bible is full. That great love of God which his word reveals is based on this condemnation. It is love to the condemned. God’s testimony to his own grace has no meaning, save as resting on or taking for granted his testimony to man’s guilt and ruin. Nor is it against man as merely a being morally diseased or sadly unfortunate that he testifies; but as guilty of death, under wrath, sentenced to the eternal curse; for that crime of crimes, a heart not right with God, and not true to his Incarnate Son.

This is a divine verdict, not a human one. It is God, not man, who condemns, and God is not a man that He should lie. This is God’s testimony concerning man, and we know that this witness is true.
